modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
issueTrackerURL = "${mod_link_issues}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile= "${mod_id}.png"
    authors = "${mod_author}"
    description = '''${mod_description}'''
    displayURL = "${mod_link_homepage}"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_version},)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_forge_version_range}"
    ordering = "NONE"
    side = "BOTH"
#[[dependencies.${mod_id}]]
#    modId="quad"
#    mandatory = true
#    versionRange="${quad_version_range}"
#    ordering="AFTER"
#    side="BOTH"