# Gradle

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties

mod_id=examplemod
mod_name=ExampleMod
mod_version=1.0.0
mod_license=MIT
mod_group=dev.lieonlion.examplemod
mod_author=LieOnLion
mod_description=The description of your mod. \nAccepts multilines.
# Links
mod_link_homepage=https://lieonlion.dev/
mod_link_sources=https://github.com/LieOnLion/examplemod
mod_link_issues=https://github.com/LieOnLion/examplemod/issues

# Common

minecraft_version=1.21.5
minecraft_fabric_version_range=>=1.21.4 <=1.21.5
minecraft_neo_version_range=[1.21.4, 1.21.5)
java_version=21

# Fabric

fabric_version=0.119.5+1.21.5
fabric_loader_version=0.16.10

# NeoForge

neoforge_version=21.5.75
neoforge_loader_version_range=[4,)
neo_form_version=1.21.5-20250325.162830
# ParchmentMC
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Dependencies

# Quad Properties
quad_version=1.2.13
quad_version_range=~1.2.12

# Sodium Properties
sodium_version=0.6.13

# ModMenu Properties
modmenu_version=14.0.0-rc.2